### ISSUE TITLE
有没有部署文档？

### ISSUE THREAD

**Issue by NICHX** [moke8/aishuati-plus-api#2]

**Comment by NICHX** [comment]
大概调通了，wechat修改\utils\global.js中的baseurls，api修改\utils\global.js中的appid和secrect（在微信小程序后台获得），admin修改.env.production和.env.development   api里面有个WXBizDataCrypt.js文件中的new Buffer修改为new Buffer.from

**Comment by moke8** [comment]
额，我在README里写了的呀。。。

[配置](https://github.com/moke8/aishuati-plus-api#%E9%85%8D%E7%BD%AE)
[小程序配置](https://github.com/moke8/aishuati-plus-api#%E5%B0%8F%E7%A8%8B%E5%BA%8F%E9%85%8D%E7%BD%AE)
utils/global.js

[数据库配置](https://github.com/moke8/aishuati-plus-api#%E6%95%B0%E6%8D%AE%E5%BA%93%E9%85%8D%E7%BD%AE)
sql/index.js

**Comment by NICHX** [comment]
> 额，我在README里写了的呀。。。
> 
> [配置](https://github.com/moke8/aishuati-plus-api#%E9%85%8D%E7%BD%AE) [小程序配置](https://github.com/moke8/aishuati-plus-api#%E5%B0%8F%E7%A8%8B%E5%BA%8F%E9%85%8D%E7%BD%AE) utils/global.js
> 
> [数据库配置](https://github.com/moke8/aishuati-plus-api#%E6%95%B0%E6%8D%AE%E5%BA%93%E9%85%8D%E7%BD%AE) sql/

谢谢了，第一次用nodejs，研究半天才整明白😅
